---
title: "OSBS Git"
output: html_document
---
Agenda 4/6/18:

1. Reviewed GitHub and file structure
2. Going through a series of R demos
  a. Diagrammer: draw your own workflows
  b. Data simulation and check ANOVA
    i. graph the results
  c. Making a map of the United States
<<<<<<< HEAD:Index.Rmd
  d. Grab Andrew's data and mess with it. 
  
```{r load pkgs}
library(DiagrammeR)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(maps)
library(mapdata)
```

 
```{r Diagrammer demo}
mermaid(" 
graph TD 
 A[Make dataset]-->B[Run statistics]
C[come closer]-->B")
```

```{r simulation}
Treatment<-c(rep("Control", 50), rep("Intervention", 50))

#Generate a random set of values that are normally distributed
rand1<-rnorm(n=1000, mean=50, sd=10)
rand2<-rnorm(n=1000, mean=100, sd=10)

Measurements<-sample(rand1, length(Treatment))

dat<-data.frame(Treatment, Measurements)
glimpse(dat)


#let's query the data in different ways
dat%>%
  group_by(Treatment)%>%
  summarise(sample_size=length(Measurements))

#let's model
mod1<-aov(Measurements~Treatment, data=dat)
summary(mod1)

dat$Measurements2<-c(sample(rand1, 50), sample(rand2, 50))
dat

mod2<-aov(Measurements2~Treatment, data=dat)
summary(mod2)


```

```{r Making maps}

map()

```

```{r querying data}
length(unique(samp.dat$SpeciesID)) #What are the number of unique species IDed?

samp.dat%>%
  filter(Lat>30)
```





=======
